// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Author struct {
	ID   string  `json:"id"`
	Name string  `json:"name"`
	Bio  *string `json:"bio,omitempty"`
}

type Book struct {
	ID            string  `json:"id"`
	Title         string  `json:"title"`
	Author        *Author `json:"author"`
	PublishedYear *int    `json:"publishedYear,omitempty"`
	Genre         *string `json:"genre,omitempty"`
	Page          *int    `json:"page,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Review struct {
	ID     string  `json:"id"`
	Book   *Book   `json:"book"`
	User   *User   `json:"user"`
	Text   *string `json:"text,omitempty"`
	Rating *int    `json:"rating,omitempty"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Role     string `json:"role"`
}
